name: quote_gen_cicd

on:
  push:
   branches:
     - "*"
  pull_request:
    branches:
     - "*"

jobs:
  test:
   runs-on: ubuntu-latest

   steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install flake8 pytest pytest-cov
          python -m pip install -r requirements.txt

      - name: Run test
        run: |
          python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=. tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml